exports.REQURIED_FIELD = 'REQURIED_FIELD';
exports.NOT_FOUND = 'NOT_FOUND';
exports.ALREADY_JOIN = 'ALREADY_JOIN';
exports.NOT_FOUND_USER = 'NOT_FOUND_USER';
exports.LEFT_FROM_ROOM = 'LEFT_FROM_ROOM';
